### ISSUE TITLE
Prefetch must be configurable via Configuration Infrastructure (appsettings, environment varialbles etc) 

### ISSUE THREAD

**Issue by luizcarlosfaria** [g12-4soat/techlanches-producao#11]
https://github.com/g12-4soat/tech-lanches/blob/4f74f8267f0e592ff3f0bd23ade32f7c94d7623c/src/TechLanches/TechLanches.Adapter.RabbitMq/Messaging/RabbitMqService.cs#L29

**Comment by gabriellima09** [comment]
@luizcarlosfaria thanks for highlighting this issue, we might be proceeding as same as mentioned here g12-4soat/techlanches-producao#12.

Thanks a lot!

**Comment by g12-4soat** [comment]
Resolved at PR #1 under [commit](https://github.com/g12-4soat/techlanches-producao/pull/1/commits/6e0032a145c78d008f83a8137bcc1d960fb69ee7#diff-c34efa98ebdbd332749baad76b3bd2c9ece6d24080e3b6a744f3e1162d2beaf3)
